version: '3'

services:
  rust-atomizer:
    build: .
    volumes:
      - .:/work  # Mount the current directory for the tool itself
      - ${SOURCE_PATH}:${CONTAINER_PATH}  # Mount the target Rust project
    working_dir: /work
    command: ${CONTAINER_PATH} ${REPO_ID}